### ISSUE TITLE
`producer:subscribe(selector)` not calling when the state changes in the same frame.

### ISSUE THREAD

**Issue by Aulkhami** [littensy/reflex#22]
When changes are repeatedly made in a `Heartbeat` or `RenderStepped` connection, the `subscribe()` method doesn't detect the changes.

**Comment by littensy** [comment]
This is the [intended behavior](https://littensy.github.io/reflex/docs/reference/reflex/producer#returns-4) (see caveats) - Reflex will batch updates by running subscriptions on the next frame after a state change to reduce calls to listeners. A subscription is called at most once per frame with the latest state.

If you want to immediately fire listeners, you can call `producer:flush()`.
